### ISSUE TITLE
Add links external links for cozy.

### ISSUE THREAD

**Issue by S1MB10T3** [cozy-nyc/cozy-nyc#17]
- [x] Add link for the devsite [dev.cozy.nyc](dev.cozy.nyc)
- [x]  Add link for the api [api.cozy.nyc](api.cozy.nyc)
- [x]  Add link for the git repo [github.com/cozy-nyc/cozy-nyc/](https://github.com/cozy-nyc/cozy-nyc/)

**Comment by Rantahu** [comment]
Icons still needed!
